"""Add GPS and job filter fields

Revision ID: 892ec97061e2
Revises: 
Create Date: 2026-08-23 15:41:09.954919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892ec97061e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.alter_column('two_factor',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('allow_applications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('allow_job_posting',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('job_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('hr_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('field',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('working_days',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('timing',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('user_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('quick_apply',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('date_posted',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('posted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_at', sa.TEXT(), nullable=True))
        batch_op.alter_column('date_posted',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('quick_apply',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('user_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('timing',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('working_days',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('field',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.alter_column('contact_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('hr_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('job_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('allow_job_posting',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('allow_applications',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('two_factor',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
